services:
  - type: web
    name: ai-for-developers-project-386
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /
